# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95ceb00248998c01337eef76c1900edb4bbcbf823f7c723ce41cb7c881585efd9f3e74b45acc92f96886b9ac4dc8e5f0343220b2bd2d3a1fbc6193d3ecea66b4

test:
  secret_key_base: b81022ba235ea12de828a47f50fcde31d807c0effcf173e26e403a56003f272a6edd754784138581fec9b7eab4ed1865d5487de45f011a4d019a7cea6ba91430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
